config/routes.rb
TagConda::Application.routes.draw do

  get 'how-it-works' => 'home#howitworks', :as => :how_it_works
  get 'about' => 'home#about', :as => :about
  get 'embed' => 'home#embed', :as => :embed
  get 'search' => 'search#search'
  get '/search/proxy' => 'search#proxy'
  get '/search/brands' => 'search#brands'
  get '/search/retailers' => 'search#retailers'
  get '/tags' => 'tags#index'

  get '/heartbeat' => 'home#heartbeat'

  post '/tags' => 'tags#create'
  delete '/tags' => 'tags#destroy'

  get '/tags/edit' => 'tags#edit'

  get '/tags/recent' => 'tags#recent'

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  get 'home/index'

end

app/views/layouts/_footer.html.slim
#footer-white
  .container
    .row
      .col-sm-3.menu
        h3 Overview
        ul
          li
            a href="features.html"  Features
          li
            a href="services.html"  Services
          li
            a href="pricing.html"  Pricing
          li
            a href="support.html"  Support
          li
            a href="blog.html"  Blog
          li
            a href="blog.html"  Coming soon
      .col-sm-3.menu
        h3 Menu
        ul
          li
            a href="features.html"  About us
          li
            a href="services.html"  Contact us
          li
            a href="aboutus.html"  Jobs
            a.hiring href="aboutus.html"
              | We're hiring!
          li
            a href="support.html"  Portfolio
          li
            a href="blog.html"  Status
      .col-sm-2.menu
        h3 Social
        ul
          li
            a href="features.html"  Youtube
          li
            a href="services.html"  Facebook
          li
            a href="pricing.html"  Twitter
      .col-sm-4.newsletter
        .signup.clearfix
          p
            | Sign up for the newsletter and we'll inform you of updates, offers and more.
          form
            input.form-control name="email" placeholder=("Your email address") type="text" /
            input type="submit" value=("Sign up") /
        a href="#"
          img alt="twitter" src="assets/images/social/social-tw.png" /
        a href="#"
          img alt="dribbble" src="assets/images/social/social-dbl.png" /
    .row.credits
      .col-md-12
        | Copyright © 2014. React

app/views/layouts/_messages.html.slim
javascript:
  var msgs =  #{raw flash.to_json};
  $(msgs).each(function(idx, arr){
      var name = arr[0];
    var msg = arr[1];
      $.bootstrapGrowl(msg, {
		  ele: 'body', // which element to append to
		  type: name == "notice" ? "success" : name, // (null, 'info', 'danger', 'success')
		  offset: {from: 'top', amount: 120}, // 'top', or 'bottom'
		  align: 'right', // ('left', 'right', or 'center')
		  width: 250, // (integer, or 'auto')
		  delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
		  allow_dismiss: true, // If true then will display a cross to close the popup.
		  stackup_spacing: 10 // spacing between consecutively stacked growls.
		});
	});

app/views/layouts/_navigation.html.slim
header.navbar.navbar-inverse class="#{nav_class(controller_name, action_name)}" role="banner"
  .container
    .navbar-header
      button.navbar-toggle data-target=".bs-navbar-collapse" data-toggle="collapse" type="button"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"=  t('meta.title')
    nav.collapse.navbar-collapse.bs-navbar-collapse role="navigation"
      ul.nav.navbar-nav.navbar-right
        /li
        /  = link_to "About", about_path
        /li
        /  = link_to "How it Works", how_it_works_path
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              = current_user.full_name
              b.caret
            ul.dropdown-menu
              li
                = link_to t('navigation.logout'), destroy_user_session_path, :method=>'delete'
              /li= link_to 'Edit account', edit_user_registration_path
              - if current_user.has_role? :admin
                li= link_to 'Admin', users_path
        - else
          li= link_to 'Login', new_user_session_path
          li= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
          li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="UTF-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    title= content_for?(:title) ? yield(:title) : t('meta.title')
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    = stylesheet_link_tag "includes/application", media: "all", "data-turbolinks-track" => false
    = javascript_include_tag "includes/application", "data-turbolinks-track" => false
    = csrf_meta_tags
    = yield(:head)

    /![if lt IE 9]
      | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script
  body class=("editor #{controller_name} #{action_name}")
    = render 'layouts/navigation'
    = render 'layouts/messages'
    = yield
    = render 'layouts/analytics'


    // This will be used to contain the products till the images are loaded
    #cachedImages

app/views/layouts/company.html.slim
doctype html
html
  head
    meta charset="UTF-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    title= content_for?(:title) ? yield(:title) : t('meta.title')
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    = stylesheet_link_tag "includes/application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "includes/application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield(:head)


    /![if lt IE 9]
      | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script
  body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    = yield
    = render 'layouts/footer'

app/views/layouts/editor.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport"
      title= content_for?(:title) ? yield(:title) : t('meta.title')
      meta content=(content_for?(:description) ? yield(:description) : t('meta.description')) name="description"
        = stylesheet_link_tag    "includes/editor", media: "all"
        = csrf_meta_tags
      = yield(:head)
      /![if lt IE 9]
        | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script
  body class=("editor #{controller_name} #{action_name}")
    = yield
    = javascript_include_tag "includes/editor"
    = render 'layouts/analytics'

    #cachedImages

app/views/layouts/signup.html.slim
doctype html
html
  head
    meta charset="UTF-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    title= content_for?(:title) ? yield(:title) : t('meta.title')
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    = stylesheet_link_tag "includes/application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "includes/application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield(:head)
    /![if lt IE 9]
      | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script
  body class="#{body_class(controller_name, action_name)}"
    = yield
    = render 'layouts/analytics'

app/views/layouts/test.html.slim
doctype html
html lang="en"
  = render partial: 'layouts/application/head'

  body.no-skin
    = render partial: 'layouts/application/navbar'

    #main-container.main-container
      javascript:
        try{ace.settings.check('main-container' , 'fixed')}catch(e){}
      = render partial: 'layouts/application/sidebar'

      .main-content
        = render partial: 'layouts/application/breadcrumbs'

        .page-content
          = render partial: 'layouts/application/companies_select_box'

          .page-content-area
            .row
              .col-xs-12
                /! PAGE CONTENT BEGINS
                - if content_for?(:page_header)
                  = yield(:page_header)
                - else
                  = render 'layouts/application/page_header'

                = bootstrap_flash

                = yield
                /! PAGE CONTENT ENDS
              /! /.col
            /! /.row
          /! /.page-content-area
        /! /.page-content
      /! /.main-content
      / = render partial: 'layouts/application/footer'

      a#btn-scroll-up.btn-scroll-up.btn.btn-sm.btn-inverse href="#"
        i.ace-icon.fa.fa-angle-double-up.icon-only.bigger-110

    = render partial: 'layouts/application/foot'